FROM golang:latest

RUN mkdir /app
WORKDIR /app
ENV CONFIG_PATH=./configs/remote.yaml
ENV POSTGRES_PASS=admin

COPY go.mod go.sum ./
RUN go mod download

COPY ./migrations ./migrations
COPY ./cmd/migrator ./cmd/migrator
COPY ./configs/remote.yaml ./configs/remote.yaml
COPY ./internal/config ./internal/config
COPY ./internal/errors ./internal/errors

RUN go build -o main ./cmd/migrator/main.go

CMD [ "./main" ]